# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

ruby File.read(File.join(__dir__, '.ruby-version')).strip

gem 'fastlane'
gem 'aws-eventstream'
gem 'cocoapods', '~> 1.13'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
